### ISSUE TITLE
Computation of % for small values seems wrong

### ISSUE THREAD

**Issue by Seer-Sir** [seer-pm/demo#71]
Here it should be 0.7% and it is displayed as 1.6%
![image](https://github.com/user-attachments/assets/1289f0f9-0620-434f-b650-c10d89a5c241)

**Comment by greenlucid** [comment]
<img width="668" alt="image" src="https://github.com/user-attachments/assets/d589a10e-a5ec-4006-92df-8dfe9d27f683">

Had a clutch this was because it was simulating a buy in order to get the market value. The issue is that it's attempting a large buy. Which happens to be 1000 usd
If you put something like 10 usd, the odds are less pronounced. In fact all of the odds changed.

<img width="749" alt="image" src="https://github.com/user-attachments/assets/9d0116ab-04f8-45ab-9b83-ec75558acabc">
